apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spin-halyard
  namespace: spinnaker 
  labels:
    app: spin
    stack: halyard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin
      stack: halyard
  template:
    metadata:
      labels:
        app: spin
        stack: halyard
    spec:
      containers:
      - name: halyard-daemon
        # todo - make :stable or digest of :stable
        image: opsmx11/halyard:stable
        imagePullPolicy: Always
        command:
        - /bin/sh
        args:
        - -c
        - "cp -R /home/builder/staging/.hal /home/builder/.hal;sh /opt/run_halyard.sh"
        readinessProbe:
          exec:
            command:
            - wget
            - -q
            - --spider
            - http://localhost:8064/health
        ports:
        - containerPort: 8064
        volumeMounts:
        - name: halconfig
          mountPath: /home/builder/staging/.hal/config
          subPath: config
        - name: kubeconfig
          mountPath: /home/builder/staging/.kube/config
          subPath: config
        - name: externalipconfig
          mountPath: /home/builder/staging/.hal/default/service-settings/deck.yml
          subPath: deck.yml
        - name: externalipconfig
          mountPath: /home/builder/staging/.hal/default/service-settings/gate.yml
          subPath: gate.yml
        - name: artifactsconfig
          mountPath: /home/builder/staging/.hal/default/service-settings/redis.yml
          subPath: redis.yml         
      volumes:
      - name: halconfig
        configMap:
          defaultMode: 420
          name: halconfig
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: kubeconfig
      - name: externalipconfig
        configMap: 
          defaultMode: 420
          name: externalipconfig
      - name: artifactsconfig
        configMap: 
          defaultMode: 420
          name: artifactsconfig

---

apiVersion: v1
kind: Service
metadata:
  name: spin-halyard
  namespace: spinnaker 
spec:
  ports:
    - port: 8064
      targetPort: 8064
      protocol: TCP
  selector:
    app: spin
    stack: halyard
  type: ClusterIP
  
---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: spinnaker
  name: externalipconfig
data:
  gate.yml: |
    host: 0.0.0.0
  deck.yml: |
    host: 0.0.0.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: spinnaker
  name: artifactsconfig
data: 
  redis.yml: |
    artifactId: opsmx11/redis:v1.0.4
